# chmod 666 the socket so the nginx user can read it
# *don't* use these permissions in production! instead, for example,
# make the user running these commands in the same group as nginx
# also no need to disable sendfile, we do this due to a VirtualBox bug
web: uwsgi -s /tmp/uwsgi.sock -w velo_monitor:wsgi --chmod-socket=666 --disable-sendfile
worker: python -m velo_monitor.worker
redis: redis-server /usr/local/etc/redis.conf
